# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bdKvHA63MFeAlY_BoU8t7DuxokzIoEj0
"""

from tkinter import*

import datetime
import time
import winsound
import playsound as ps

def alarm(set_alarm_timer):
    while True:
        time.sleep(1)
        current_time = datetime.datetime.now()
        now=current_time.strftime("%H:%M:%S")
        date=current_time.strftime("%d/%m/%Y")
        print(now)
        
        if now==set_alarm_timer:
            print("Time to Wake Up")
            #ps.playsound("E:\ENGLISH AND REVERBED\Samsung.mp3")
            #Add sound of your wish
            break
        
def actual_time():
    set_alarm_timer=f"{hour.get()}:{min.get()}:{sec.get()}"
    alarm(set_alarm_timer)


window=Tk()

canvas=Canvas(window,height=500,width=500 )
canvas.create_oval(100,100,400,400,fill="navy blue",width=20,outline="orchid")
#canvas.create_text(250,165,text="Alarm Clock",font="Algerian")
time_format=Label(canvas,text="Enter time in 24 hour format",fg="red",bg="black",font="Cambria").place(x=160,y=430)

addTime=Label(canvas,text="Alarm Clock",font="Algerian",width=15,bg="aquamarine").place(x=175,y=165)

addTime=Label(canvas,text="Hour  |  Min  |  Sec",font=75,width=20).place(x=160,y=215)


hour=StringVar()
min=StringVar()
sec=StringVar()
                  
                  
hourTime=Entry(canvas,textvariable=hour,bg="pink",width=20).place(x=160,y=255)
minTime=Entry(canvas,textvariable=min,bg="pink",width=15).place(x=237,y=255)
secTime=Entry(canvas,textvariable=sec,bg="pink",width=10).place(x=280,y=255)
                  
submit=Button(canvas,text="Set alarm",fg="Blue",font="Cambria",width=10,command=actual_time).place(x=205,y=290)
                  




canvas.pack()
window.mainloop()